apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: signer
spec:
  serviceAccountName: signer
  containers:
    - name: debug
      image: alpine:3.14.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      command:
        - sh
        - -c
        - 'echo "Done"'
  volumes:
    - name: config-volume
      configMap:
        name: investigate-go-configmap-keyconf