apiVersion: v1
kind: ServiceAccount
metadata:
  name: investigate-go-configmap
  namespace: investigate
---
# A role for administering pods in the signer namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: signer
  name: pod-admin
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Give serviceaccount permission to administer pods in the signer namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: signer
  name: investigate-go-configmap-administers-pods
subjects:
  - kind: ServiceAccount
    namespace: investigate
    name: investigate-go-configmap
roleRef:
  kind: Role
  name: pod-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: investigate-go-configmap
  namespace: investigate
spec:
  serviceAccountName: investigate-go-configmap
  containers:
    - name: investigate-go-configmap
      image: investigate-go-configmap:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
---
#
# Signer pod
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: signer
  namespace: signer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: investigate-go-configmap-keyconf
  namespace: signer
data:
  config.yaml: |
    key: value
---